# Generated by Django 5.0.6 on 2024-07-09 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabanas', '0002_contactform_delete_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='ContactFormModel',
        ),
    ]
